// VoiceMail Constants
export const GET_ALL_VMBOXES = 'GET_ALL_VMBOXES'
export const GET_ALL_MESSAGES_ON_AN_ACCOUNT = 'GET_ALL_MESSAGES_ON_AN_ACCOUNT'
export const GET_ALL_VMBOXES_SUCCESS = 'GET_ALL_VMBOXES_SUCCESS'
export const GET_ALL_MESSAGES_ON_AN_ACCOUNT_SUCCESS = 'GET_ALL_MESSAGES_ON_AN_ACCOUNT_SUCCESS'
export const SET_SELECTED_VMBOX_ID = "SET_SELECTED_VMBOX_ID"
//  Authentication
export const GET_NEW_TOKEN_SUCCESS = 'GET_NEW_TOKEN_SUCCESS'
export const RESET_AUTH_TOKEN = 'RESET_AUTH_TOKEN'

//  Global
export const SENDING_API_REQUEST = 'SENDING_API_REQUEST'
export const FAIL_API_REQUEST = 'FAIL_API_REQUEST'
export const DELETE_SYSTEMMESSAGE = "DELETE_SYSTEMMESSAGE"
export const SET_SYSTEMMESSAGE = "SET_SYSTEMMESSAGE"
export const GET_ALL_CALL_FLOW_ON_AN_ACCOUNT_SUCCESS = "GET_ALL_CALL_FLOW_ON_AN_ACCOUNT_SUCCESS"
export const GET_ALL_DEVICES_ON_AN_ACCOUNT_SUCCESS = 'GET_ALL_DEVICES_ON_AN_ACCOUNT_SUCCESS'
export const GET_ALL_NUMBER_ON_AN_ACCOUNT_SUCCESS = 'GET_ALL_NUMBER_ON_AN_ACCOUNT_SUCCESS'
export const GET_ALL_FAXES_ON_AN_ACCOUNT_SUCCESS = 'GET_ALL_FAXES_ON_AN_ACCOUNT_SUCCESS'

//notification
export const GET_ALL_NOTIFICATION = 'GET_ALL_NOTIFICATION'
export const SET_LANGUAGE = 'SET_LANGUAGE'